# root: true
# enable ES6
parserOptions:
  ecmaVersion: 2017
  sourceType: "module"
  ecmaFeatures:
    jsx: true # enable React's JSX

# use the rules of eslint-config-airbnb
# and the recommended rules of eslint-plugin-meteor
extends:
  - airbnb-base

# registerenvironments
env:
  browser: true
  node: true
  es6: true

rules:
  # overwrite some rules (avoid semicolons) 
  semi: [2, 'never']
  no-unexpected-multiline: 2
  no-throw-literal: 0
  prefer-template: 0
  dot-notation: 0
  func-names: 0
  comma-dangle: 0
  prefer-arrow-callback: 0
  arrow-parens: 0
  import/no-extraneous-dependencies: 0
  import/no-absolute-path: 0
  import/no-unresolved: 0
  import/extensions:
    - off
    - never
  max-len:
    - error
    - code: 120
      ignoreComments: true
      ignoreUrls: true

globals:
  QRLLIB: true
  ethereum: true
  describe: true
  it: true
